# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  vmImage: windows-latest

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.6'
          addToPath: true
          architecture: 'x64'
      - script: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
          pyinstaller --onefile .\RandomNumberGeneratorApp.py
        displayName: 'Build application package'
      - script: |
          python.exe $(System.DefaultWorkingDirectory)/dist/RandomNumberGeneratorApp.exe 10 20
        displayName: 'Test application'
      - publish: $(System.DefaultWorkingDirectory)/dist/RandomNumberGeneratorApp.exe
        artifact: RandomNumberGeneratorApp
        displayName: 'Create .exe artifact for release'