# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- main

pool:
  vmImage: windows-latest

stages:
- stage: Build
  jobs:
  - job: Build
    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.6'
          addToPath: true
          architecture: 'x64'
      - script: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pyinstaller
          pyinstaller --onefile .\main.py
        displayName: 'Build application package'

- stage: Test
  jobs:
  - job: Test
    steps:
    - script: |
        python.exe $(System.DefaultWorkingDirectory)/dist/main.exe 10 20
      displayName: 'Test application'
      condition: 

- stage: PublishArtifact
  jobs:
  - job: PublishArtifact
    steps:
    - publish: $(System.DefaultWorkingDirectory)/dist/main.exe
      artifact: RandomNumberGenerator.exe
    displayName: 'Create .exe artifact for release'